import 'package:flutter/material.dart';
import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "homet1": "الخدمات",
          "homet2": "المصابغ",
          "homet3": "الاقرب اليك",
          "viewall": "عرض الكل",
          "online": "متاح الان",
          "offline": "مغلق الان",
          "search": "البحث",
          "wash": "غسيل",
          "iron": "كي",
          "delivery": "توصيل",
          "homebar": "الرئيسية",
          "ordersbar": "الطلبات",
          "favbar": "المفضلة",
          "profile": "الحساب",
          "cancel": "الغاء",
          "pending": "انتظار",
          "progress": "قيد المعالجة",
          "complete": "منفذ",
          "username": "اسم المستخدم",
          "gender": "الجنس",
          "phone": "رقم الهاتف",
          "male": "ذكر",
          "female": "انثى",
          "all": "الجميع",
          "order": "طلب",
          "quickorder": "طلب سريع",
          "washandiron": "غسيل و كي",
          "addtocart": "اضافة الى السلة",
          "clothes": "الملابس",
          "lang": "اللغة",
          "email": "البريد الالكتروني",
          "password": "كلمة السر",
          "cpassword": "تأكيد كلمة المرور",
          "login": "تسجيل الدخول",
          "singup": "تسجيل حساب",
          "welcome": "اهلا بك في عالم الغسيل",
          "createaccount": "انشاء حساب",
          "cart": "السلة",
          "empty": "فارغة",
          "confirm": "تأكيد",
          "total": "الاجمالي",
          "placeorder": "ارسال الطلب",
          "finalprice": "السعر الاجمالي",
          "confirmorder": "تأكيد الطلب",
          "thankmessage": "شكرا لاختيارك لنا",
          "time": "سيصل طلبك خلال مدة اقصاها 24 ساعة",
          "timevip": "سيصل طلبك خلال مدة اقصاها 6 ساعات",
          "numofclothes":"عدد القطع",
          "logout":"تسجيل الخروج"
        },
        "en": {
          "homet1": "Services",
          "homet2": "Laundries",
          "homet3": "Neer You",
          "viewall": "View All",
          "online": "Online",
          "offline": "Offline",
          "search": "Search",
          "wash": "Wash",
          "iron": "Iron",
          "delivery": "Delivery",
          "homebar": "Home",
          "ordersbar": "Orders",
          "favbar": "Favorite",
          "profile": "Profile",
          "cancel": "Cancel",
          "pending": "Pending",
          "progress": "in progress",
          "complete": "Complete",
          "username": "Username",
          "gender": "Gender",
          "phone": "Phone Number",
          "male": "Male",
          "female": "Female",
          "all": "All",
          "order": "Order",
          "quickorder": "Quick Order",
          "washandiron": "Iron and Wash",
          "addtocart": "Add to cart",
          "clothes": "Clothes",
          "lang": "Language",
          "email": "Email",
          "password": "Password",
          "cpassword": "Confirm password",
          "login": "Login",
          "singup": "Signup",
          "welcome": "Welcome to a cleaning world",
          "createaccount": "Create Account",
          "cart": "Cart",
          "empty": "Empty",
          "confirm": "Confirm",
          "total": "Total",
          "placeorder": "Send Order",
          "finalprice": "Final Price",
          "confirmorder": "Confirm Order",
          "thankmessage": "Thank you for chossing us",
          "time": "Your order will be delivered within a maximum of 24 hours",
          "timevip": "Your order will be delivered within a maximum of 6 hours",
          "numofclothes":"Clothes Count",
          "logout":"Log Out"
        }
      };
}
